// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => web;

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9wYXmHDyvlZQWYQtNiK0nmg8vdGUcReQ',
    appId: '1:148247231661:web:5e6a849a6c74db346d9a24',
    messagingSenderId: '148247231661',
    projectId: 'jess-yen',
    authDomain: 'jess-yen.firebaseapp.com',
    storageBucket: 'jess-yen.firebasestorage.app',
    measurementId: 'G-S8PCV8B8MP',
  );

}