name: resume
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.0 
  logger: ^2.4.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  layout: ^1.0.5
  visibility_detector: ^0.4.0+2
  animated_text_kit: ^4.2.3
  responsive_builder: ^0.7.1
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/icon/ic_gmail.svg
    - assets/icon/ic_linkedin.svg
    - assets/icon/ic_github.svg
